spring:
  datasource:
    url: jdbc:h2:mem:announcement
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /konsola
  flyway:
    enabled: true
    user: sa
    password:
    schemas: announcement
    baseline-on-migrate: true
    locations: classpath:db/migration
#logging:
#  level:
#    root: DEBUG