spring:
  data:
    rest:
      basePath: /api/v1
  datasource:
    url: jdbc:h2:mem:announcement
    username: admin
    password: password
  h2:
    console:
      enabled: true
      path: /database
  flyway:
    enabled: true
    baseline-on-migrate: true